/*
 Multi Select jQuery Plugin - v1.0.0-beta1

 Copyright 2017 Ganpat S Rajpurohit, Jaipur.

 Licensed MIT
*/
"function"!==typeof Object.create&&(Object.create=function(a){function k(){}k.prototype=a;return new k});
(function(a,k,l,n){a.strip_tags=function(a){return(a||"").replace(/(<([^>]+)>)/ig,"")};var m={_init:function(c,d){var b=this;this.settings=a.extend({},a.fn.multi_select.defaults,d);this.$el=a(c);this.selectedValues=[];this.basicClass="multi-button";this.selectColors="green blue aqua red yellow maroon purple".split(" ");var e=this.settings;a(c).each(function(){a(this).css({position:"relative",width:e.buttonWidth});$wrapper=b._styleElement(a(this));$list=b._createList(a(this));a(this).append($list);
a(this).data("list",$list);b._addEvents(this);b._setSelected()})},init:function(){this._init.call(this,this.$el,this.settings)},_createList:function(c){var d=this,b=d.settings,e=this.getData(),f=b.selectedIndexes;b=b.listMaxHeight;var g={};b&&(g={"overflow-x":"hidden","overflow-y":"auto",display:"none","max-height":b});var h=a("<ul />",{"class":"multi-menu"}).css(g).data("trigger",c);c=a("<li />",{"class":"control"});$selAllNone=a("<a />",{"class":"select-all-none",text:"Select All"}).on("click",
function(a){a.preventDefault();d._selectToggle(this)});c.append($selAllNone);h.append(c);0<e.length&&a.each(e,function(c,b){var e="";-1!==a.inArray(parseInt(b.index),f)&&(e="selected");e=a("<li />",{"class":"list-items "+e,data:{id:b.index,text:a.strip_tags(b.text)}});var g=a("<a />",{}),k=a("<span />",{"class":"text",html:a.strip_tags(b.text)}),l=a("<span />",{"class":"check-mark",html:"&#10004;"});g.append(k).append(l);e.append(g).on("click",function(){a(this).toggleClass("selected");d._setSelected(a(this))});
h.append(e)});return this.$list=h},_addEvents:function(c){var d=this;a(c);var b=d.settings,e=b.duration,f=b.easing;a(c).on("click",function(b){b.preventDefault();a(this);a(c).addClass("open");b=a(c).find("ul");"slide"==f?b.slideDown(e,function(){}):"fade"==f&&b.fadeIn(e,function(){});d._hideList()});a(c).bind("gs.hidden",c,function(b,c){a(this).hasClass("open")?console.log("open"):console.log("not open")})},_styleElement:function(c){var d=this.settings,b=[];b.push(this.basicClass);b.push("button-"+
d.selectSize);b.push("button-"+d.selectColor);d.fillButton&&b.push("fill");b=b.join(" ");d=a("<span />",{"class":"button-text",html:d.selectText});c.addClass(b).html(d)},getData:function(){var a=this.settings.sortByText?this._sortByText():this._sortByKey();this.settings.data=a;return this.settings.data},_sortByText:function(){var c=[];a.each(this.settings.data,function(a,b){c.push({text:b,index:a})});c.sort(function(a,b){return a.text>b.text?1:a.text<b.text?-1:0});return c},_sortByKey:function(){var c=
[];a.each(this.settings.data,function(a,b){c.push({text:b,index:a})});return c},_checkSelected:function(){var a=this.$el,d=a.data("list"),b=d.find("li:not(.control)");d=d.find("li.selected:not(.control)");b.length==d.length?a.find(".select-all-none").text("Select None"):a.find(".select-all-none").text("Select All")},getSelectedValues:function(){return this.settings.selectedValues},clearValues:function(){var a=this.$el;a.data("list").find("li.selected").removeClass("selected");this.settings.selectedValues=
[];a.find(".button-text").text(this.settings.selectText)},_selectToggle:function(c){var d=this.$el,b=this.settings,e=d.find(".button-text");d=d.data("list");var f=d.find("li:not(.control)");c=a(c);if("Select All"==c.text()){d.find("li:not(.control)").addClass("selected");c.text("Select None");var g=[],h=[];0<f.length?(f.each(function(b,c){g[b]=a(this).data("id");h.push(a(this).data("text"))}),f.length<=b.selectedCount?e.text(h.join(", ")):e.text("Selected ("+f.length+")")):e.text(this.settings.selectText);
this.settings.selectedValues=g;this.settings.onSelect.call(this,this.settings.selectedValues);this._checkSelected()}else this.clearValues(),c.text("Select All"),this.settings.onSelect.call(this,this.settings.selectedValues)},_setSelected:function(c){var d=this.$el;c=this.settings;var b=d.data("list").find("li.selected");d=d.find(".button-text");var e=[],f=[];0<b.length?(b.each(function(b,c){f[b]=a(this).data("id");e.push(a(this).data("text"))}),b.length<=c.selectedCount?d.text(e.join(", ")):d.text("Selected ("+
b.length+")")):d.text(this.settings.selectText);this.settings.selectedValues=f;this.settings.onSelect.call(this,this.settings.selectedValues);this._checkSelected()},_hideList:function(){var c=this.$el,d=this.settings,b=d.duration,e=d.easing;a(l).on("click",function(d){c.each(function(){var c=a(this).find(".multi-menu");if(!a(this).is(d.target)&&0===a(this).has(d.target).length&&0===c.has(d.target).length){var f=a(this);"slide"==e?c.slideUp(b,function(){f.removeClass("open")}):"fade"==e&&c.fadeOut(b,
function(){f.removeClass("open")})}})})}};a.fn.multi_select=function(c){if(a.isPlainObject(c))return this.each(function(){var b=Object.create(m);b._init(this,c);a(this).data("multi_select",b)});if("string"===typeof c&&0!==c.indexOf("_")){var d=a(this).data("multi_select");return d[c].apply(d,a.makeArray(arguments).slice(1))}};a.fn.multi_select.defaults={selectColor:"red",selectSize:"small",selectText:"Select",selectedCount:3,duration:300,easing:"slide",listMaxHeight:200,selectedIndexes:null,sortByText:!1,
fillButton:!1,data:{},buttonWidth:"100%",onSelect:function(){return!0}}})(jQuery,window,document);
